### ISSUE TITLE
Missing Access

### ISSUE THREAD

**Issue by LandyLane** [victornpb/deleteDiscordMessages#27]
Using the latest version from the repo I get this error when attempting to delete:

```
Started at 03/12/2019, 11:54:16
authorId="my id" guildId="guild id" channelId="channel id" afterMessageId="" beforeMessageId="" hasLink=false hasFile=false
Error searching messages, API responded with status 403!
	{"message":"Missing Access","code":50001}
```

Using Chrome for this.

**Comment by victornpb** [comment]
Are you trying it in a server, dm or dm group?

**Comment by EwolBash** [comment]
@victornpb I'm having the same issue but it's in an NSFW marked channel. Any way around it?

**Comment by victornpb** [comment]
As of now I was not able to reproduce this issue. I have to investigate. Are you able to delete messages in other place other than that nsfw channel?

**Comment by LandyLane** [comment]
> As of now I was not able to reproduce this issue. I have to investigate. Are you able to delete messages in other place other than that nsfw channel?

Yes, any channel that is not marked NSFW works fine.

**Comment by EwolBash** [comment]
I've deleted all messages except those in the NSFW channels. So same as LandyLane.

**Comment by YraelOramara** [comment]
Easily fixed, simply change the endpoint on line 145 from:
```API_SEARCH_URL = `https://discordapp.com/api/v6/guilds/${guildId}/messages/`; // Server```
to
```API_SEARCH_URL = `https://discordapp.com/api/v6/channels/${channelId}/messages/`; // Server```
(i.e. may as well get rid of the if statement altogether)

Worked for me in both regular channels and those tagged NSFW.

[As far as I can see](https://discordapp.com/developers/docs/resources/guild), there is no longer an endpoint for messages under /guilds/.

**Comment by EwolBash** [comment]
I can confirm @YraelOramara 's fix works.

**Comment by victornpb** [comment]
@YraelOramara I added the condition to fix #24, I just replicated the client behavior. Idk if they changed it again since then. They look kinda redundant tbh, so I wouldn't be surprised if they remove one of them.

Deleting messages in NSFW channels is something I never tested against before, so IDK if the have a different behavior for them. I'd have to check.

Anyway, discord is going under changes, and they are having issues with the search API, so I expect that things are going to break until they stop changing the API.

**Comment by YraelOramara** [comment]
>Deleting messages in NSFW channels is something I never tested against before, so IDK if the have a different behavior for them. I'd have to check.

Need to get yourself in some more porn servers!

Anyway, the search API issue was a temporary thing over the weekend due to google cloud issues, but regarding this issue: as far as I can see, there is no reference to any of it in the [change logs](https://discordapp.com/developers/docs/change-log) either - really nice to have such a stable API **/s**

**Comment by LandyLane** [comment]
To fix the NSFW missing access, add '&include_nsfw=true' at the end of the search url after it appends all the parameters

Example:
`[ 'has', hasFile ? 'file' : undefined ],
                ]) + '&include_nsfw=true', { headers });
                lastPing = (Date.now() - s);`

**Comment by victornpb** [comment]
Fixed in the lastest version. (#37 #35)

**Comment by EwolBash** [comment]
> 
> 
> Fixed in the lastest version. (#37 #35)

Unfortunately, it is not. I have to use this version https://raw.githubusercontent.com/hnnhwng/deleteDiscordMessages/master/deleteDiscordMessages.js 

I still get error 403 on the one you updated 8 days ago.
